spring.application.name=Regioner

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/region_db
spring.datasource.username=magnus
spring.datasource.password=magnus
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
